<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class OffersFulfilment extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'method' => [ 'model' => null, 'enum' => Enum\OffersFulfilmentMethod::class, 'array' => false ],
            'schedule' => [ 'model' => null, 'enum' => Enum\OffersFulfilmentSchedule::class, 'array' => false ],
            'deliveryPromise' => [ 'model' => FulfilmentDeliveryPromise::class, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\OffersFulfilmentMethod
     */
    public $method;

    /**
     * @var Enum\OffersFulfilmentSchedule
     */
    public $schedule;

    /**
     * @var FulfilmentDeliveryPromise Specifies the expected delivery timeframe for the offer. This value will only be
     * used in combination with fulfilmentMethod 'FBR'.
     */
    public $deliveryPromise;
}
