<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class SubCategory extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     * @todo: The 'subcategories' was added manually, as it's missing from the swagger specs
     *          This should be removed and auto generated as soon as Bol has updated their specs
     */
    public function getModelDefinition(): array
    {
        return [
            'id' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'name' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'subcategories' => [ 'model' => SubCategory::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var string The id of the subcategory which the product belongs to.
     */
    public $id;

    /**
     * @var string The name of the subcategory which the product belongs to.
     */
    public $name;

    /**
     * @var SubCategory[] The subcategories which the product belongs to.
     */
    public $subcategories = [];
}
